### ISSUE TITLE
Re-write existing spec into the current fashion

### ISSUE THREAD

**Issue by joejag** [build-canaries/cctray#3]
https://www.conventionalcommits.org/en/v1.0.0-beta.3/
https://semver.org/

**Comment by GentlemanHal** [comment]
@joejag Not entirely sure what this means? Also do we still need to do it?

**Comment by joejag** [comment]
Hmm. The version number we use for the spec is like `v1` I think I had a notion of making it into something like `1.0.0` (Semantic Versions) and then leveraging Conventional Commits to auto-update the version number based off commit messages.

This seems like extreme overkill, so it was probably just me being excited back in March 2019 before a worldwide pandemic hit.
